name: ShellCheck

on:
  push:
    branches: [ "main", "weekly" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in workspace
        run: |
          pwd
          ls -al test_scripts

      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-check
          path: |
            ./
            commands/
          pattern: |
            *.sh