name: ShellCheck

on:
  push:
    branches: [ "main", "weekly" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@v1
        with:
          # Use GitHub Check annotations for results
          reporter: github-check
          # Specify multiple paths as a multi-line string
          # '.' Represents the root directory of the repository
          path: | 
            commands
            .
          pattern: "*.sh"